In [1]:
import numpy as np

In [440]:
N=8
a=[[0]*N for i in range(N)] #파이썬 2차원 배열, 모든 원소가 0인 8x8리스트 생성


In [441]:
list = [5, 2, 3, 14, 9, 2, 11, 8]

In [442]:
a[-1] = list

In [443]:
a

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [5, 2, 3, 14, 9, 2, 11, 8]]

In [214]:
list

[5, 2, 3, 14, 9, 2, 11, 8]

In [147]:
min(list)

2

In [458]:
import numpy as np
def make_matrix(input_list,N):
    a=[[0]*N for i in range(N)] #파이썬 2차원 배열, 모든 원소가 0인 NxN리스트 생성
    a[-1] = input_list
    return a

In [459]:
input_list = [5, 2, 3, 14, 9, 2, 11, 8]
test_matrix = make_matrix(input_list,8)
test_matrix

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [5, 2, 3, 14, 9, 2, 11, 8]]

#### 1. 물고기의 수가 가장 적은 어항에 물고기를 한 마리 넣는다.

In [460]:
def add_one_to_min(input_matrix):
    result_matrix = np.copy(input_matrix)
    copy_list = input_matrix[-1].copy()
    for i,value in enumerate(input_matrix[-1]):
        if value== min(input_matrix[-1]):
            copy_list[i] = value+1
    result_matrix[-1] = copy_list
    return result_matrix
    

In [451]:
test_matrix

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [5, 2, 3, 14, 9, 2, 11, 8]]

In [462]:
test_matrix_2 = add_one_to_min(test_matrix)
test_matrix_2

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 5,  3,  3, 14,  9,  3, 11,  8]])

In [215]:
new_list = a[-1].copy()
for i,value in enumerate(a[-1]):
    if value== min(a[-1]):
        new_list[i] = value+1
        
print(new_list)

[5, 3, 3, 14, 9, 3, 11, 8]


In [216]:
a[-1]= new_list

In [217]:
a

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [5, 3, 3, 14, 9, 3, 11, 8]]

#### 2. 어항을 쌓는다.

In [463]:
def stack_fish_tank(input_matrix):
    result_matrix = np.copy(input_matrix)
    pivot,w,h = 1,1,1
    idx = 0
    N=8
    while True:
        if (pivot-1+w+h>N): #종료 조건
            break
        for c in range(pivot-1, pivot-1 + w):
            for r in range(-1, -h - 1, -1):
                nextR = - w + c - pivot
                nextC = pivot-1 +w -(r+1)
                result_matrix[nextR][nextC] = result_matrix[r][c]
                result_matrix[r][c] = 0
        pivot += (idx // 2 + 1)
        if idx % 2 == 1:
            w += 1
        else:
            h += 1
        idx += 1
    return result_matrix


In [464]:
stack_matrix = stack_fish_tank(test_matrix_2)
stack_matrix

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  3,  3,  0,  0],
       [ 0,  0,  0,  0, 14,  5,  0,  0],
       [ 0,  0,  0,  0,  9,  3, 11,  8]])

In [218]:
my_list = np.array(a)

In [219]:
my_list

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 5,  3,  3, 14,  9,  3, 11,  8]])

In [220]:
pivot,w,h = 1,1,1
idx = 0
N=8
while True:
    if (pivot-1+w+h>N): #종료 조건
        break
    for c in range(pivot-1, pivot-1 + w):
        for r in range(-1, -h - 1, -1):
            nextR = - w + c - pivot
            nextC = pivot-1 +w -(r+1)
            my_list[nextR][nextC] = my_list[r][c]
            my_list[r][c] = 0
    print(my_list)
    pivot += (idx // 2 + 1)
    if idx % 2 == 1:
        w += 1
    else:
        h += 1
    idx += 1

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  5  0  0  0  0  0  0]
 [ 0  3  3 14  9  3 11  8]]
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  3  5  0  0  0  0]
 [ 0  0  3 14  9  3 11  8]]
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  3  3  0  0]
 [ 0  0  0  0 14  5  0  0]
 [ 0  0  0  0  9  3 11  8]]


In [221]:
my_list

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  3,  3,  0,  0],
       [ 0,  0,  0,  0, 14,  5,  0,  0],
       [ 0,  0,  0,  0,  9,  3, 11,  8]])

#### 3. 어항에 있는 물고기 수 조절

In [466]:
def control_fish_num(input_matrix):
    result_matrix = np.copy(input_matrix)
    dx = [0,0,-1,1]
    dy = [1,-1,0,0]
    for x in range(0,N):
        for y in range(0,N):
            for i in range(0,4):
                nextX = x + dx[i]
                nextY = y + dy[i]
                if (nextX<0) or (nextX>N-1) or (nextY<0) or (nextY>N-1):
                    continue
                if (input_matrix[nextX][nextY] ==0):
                    continue
                if (input_matrix[x][y]> input_matrix[nextX][nextY]):
                    diff = (input_matrix[x][y] - input_matrix[nextX][nextY]) //5
                    result_matrix[x][y] -= diff
                    result_matrix[nextX][nextY] += diff
    return result_matrix

In [467]:
control_matrix = control_fish_num(stack_matrix)
control_matrix

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  3,  0,  0],
       [ 0,  0,  0,  0, 10,  6,  0,  0],
       [ 0,  0,  0,  0,  9,  5, 10,  8]])

In [468]:
stack_matrix

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  3,  3,  0,  0],
       [ 0,  0,  0,  0, 14,  5,  0,  0],
       [ 0,  0,  0,  0,  9,  3, 11,  8]])

In [222]:
copy_list = my_list.copy()

In [223]:
copy_list

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  3,  3,  0,  0],
       [ 0,  0,  0,  0, 14,  5,  0,  0],
       [ 0,  0,  0,  0,  9,  3, 11,  8]])

In [224]:
dx = [0,0,-1,1]
dy = [1,-1,0,0]
for x in range(0,N):
    for y in range(0,N):
        for i in range(0,4):
            nextX = x + dx[i]
            nextY = y + dy[i]
            if (nextX<0) or (nextX>N-1) or (nextY<0) or (nextY>N-1):
                continue
            if (my_list[nextX][nextY] ==0):
                continue
            if (my_list[x][y]> my_list[nextX][nextY]):
                diff = (my_list[x][y] - my_list[nextX][nextY]) //5
                copy_list[x][y] -= diff
                copy_list[nextX][nextY] += diff

In [225]:
copy_list

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  3,  0,  0],
       [ 0,  0,  0,  0, 10,  6,  0,  0],
       [ 0,  0,  0,  0,  9,  5, 10,  8]])

#### 4. 어항을 바닥에 일렬로 놓기

In [473]:
def spread_fish(input_matrix,N):
    result_matrix = [[0]*N for i in range(N)]
    compare_list = [0]*N
    result_array = []
    for c in range(0,N):
        if np.array_equal(input_matrix[:,c],compare_list):
            continue
        for i in range(0,N):
            num = np.flip(input_matrix[:,c])[i]
            if num == 0:
                continue
            result_array.append(num)
    result_matrix[-1] = result_array
    return result_matrix

In [474]:
control_matrix

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  3,  0,  0],
       [ 0,  0,  0,  0, 10,  6,  0,  0],
       [ 0,  0,  0,  0,  9,  5, 10,  8]])

In [475]:
spread_matrix = spread_fish(control_matrix,N)
spread_matrix

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [9, 10, 5, 5, 6, 3, 10, 8]]

In [226]:
compare_list = [0]*N
compare_list

[0, 0, 0, 0, 0, 0, 0, 0]

In [227]:
compare_list = [0]*N
result_array = []
for c in range(0,N):
    if np.array_equal(copy_list[:,c],compare_list):
        continue
    for i in range(0,N):
        num = np.flip(copy_list[:,c])[i]
        if num == 0:
            continue
        result_array.append(num)

In [228]:
result_array

[9, 10, 5, 5, 6, 3, 10, 8]

In [229]:
a[-1] = result_array

In [230]:
a

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [9, 10, 5, 5, 6, 3, 10, 8]]

#### 5. 공중부양

In [428]:
a

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [9, 10, 5, 5, 6, 3, 10, 8]]

In [476]:
# 180 도 회전
def rotate_180_clockwise(list):
    new_list = np.copy(list)
    new_list = np.flip(np.append(new_list,[0]*(N-len(list))))
    return new_list

In [484]:
def fly_fish_bowls(input_matrix, N):
      result_matrix = np.copy(input_matrix)
      compare_list = [0]*N
      while True:
            zero_row = 0 
            reversed_lists = []
            if np.count_nonzero(result_matrix[-1])==2:
                  break
            for i,row in enumerate(result_matrix):       
                  if np.array_equal(row, compare_list):
                        zero_row += 1
                  if not(np.array_equal(row,compare_list)):
                        nonzero_len = np.count_nonzero(row)
                        start = N - nonzero_len
                        copy_row = np.copy(row) #deep copy
                        list = copy_row[start:start + int(nonzero_len/2)]
                        result_matrix[i][start:start + int(nonzero_len/2)] =0
                        reversed_list = rotate_180_clockwise(list)
                        reversed_lists.append(reversed_list)
                        
                        nonzero_row = N-zero_row

            for i,list in enumerate(reversed_lists):
                  result_matrix[(-1)*(i+nonzero_row+1)][:] = list
      return result_matrix

In [485]:
fly_matrix = fly_fish_bowls(spread_matrix,N)
fly_matrix

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  3,  6],
       [ 0,  0,  0,  0,  0,  0,  5,  5],
       [ 0,  0,  0,  0,  0,  0, 10,  9],
       [ 0,  0,  0,  0,  0,  0, 10,  8]])

In [426]:
copy_a = np.copy(a)
# 180 도 회전
def rotate_180_clockwise(list):
    new_list = np.copy(list)
    new_list = np.flip(np.append(new_list,[0]*(N-len(list))))
    return new_list

while True:
      zero_row = 0 
      reversed_lists = []
      if np.count_nonzero(copy_a[-1])==2:
             break
      for i,row in enumerate(copy_a):       
        if np.array_equal(row, compare_list):
              zero_row += 1
        if not(np.array_equal(row,compare_list)):
            nonzero_len = np.count_nonzero(row)
            start = N - nonzero_len
            copy_row = np.copy(row) #deep copy
            list = copy_row[start:start + int(nonzero_len/2)]
            copy_a[i][start:start + int(nonzero_len/2)] =0
            reversed_list = rotate_180_clockwise(list)
            reversed_lists.append(reversed_list)
            
            print("reversed list ",reversed_list)
            nonzero_row = N-zero_row

      print("nonzero_row ",nonzero_row)
      for i,list in enumerate(reversed_lists):
            copy_a[(-1)*(i+nonzero_row+1)][:] = list
      print(reversed_lists)

reversed list  [ 0  0  0  0  5  5 10  9]
nonzero_row  1
[array([ 0,  0,  0,  0,  5,  5, 10,  9])]
reversed list  [0 0 0 0 0 0 5 5]
reversed list  [0 0 0 0 0 0 3 6]
nonzero_row  2
[array([0, 0, 0, 0, 0, 0, 5, 5]), array([0, 0, 0, 0, 0, 0, 3, 6])]


In [432]:
copy_a

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  3,  6],
       [ 0,  0,  0,  0,  0,  0,  5,  5],
       [ 0,  0,  0,  0,  0,  0, 10,  9],
       [ 0,  0,  0,  0,  0,  0, 10,  8]])

#### 6. 물고기 조절 작업

In [486]:
control_matrix_2 = control_fish_num(fly_matrix)
control_matrix_2

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  3,  6],
       [ 0,  0,  0,  0,  0,  0,  6,  5],
       [ 0,  0,  0,  0,  0,  0,  9,  9],
       [ 0,  0,  0,  0,  0,  0, 10,  8]])

In [433]:
copy_list = np.copy(copy_a)


In [435]:
copy_list = np.copy(copy_a)

dx = [0,0,-1,1]
dy = [1,-1,0,0]
for x in range(0,N):
    for y in range(0,N):
        for i in range(0,4):
            nextX = x + dx[i]
            nextY = y + dy[i]
            if (nextX<0) or (nextX>N-1) or (nextY<0) or (nextY>N-1):
                continue
            if (copy_a[nextX][nextY] ==0):
                continue
            if (copy_a[x][y]> copy_a[nextX][nextY]):
                diff = (copy_a[x][y] - copy_a[nextX][nextY]) //5
                copy_list[x][y] -= diff
                copy_list[nextX][nextY] += diff

In [436]:
copy_list

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  3,  6],
       [ 0,  0,  0,  0,  0,  0,  6,  5],
       [ 0,  0,  0,  0,  0,  0,  9,  9],
       [ 0,  0,  0,  0,  0,  0, 10,  8]])

#### 7. 일렬로 나열

In [489]:
spread_matrix_2 = spread_fish(control_matrix_2,N)
spread_matrix_2[-1]

[10, 9, 6, 3, 8, 9, 5, 6]

In [437]:
compare_list = [0]*N
result_array = []
for c in range(0,N):
    if np.array_equal(copy_list[:,c],compare_list):
        continue
    for i in range(0,N):
        num = np.flip(copy_list[:,c])[i]
        if num == 0:
            continue
        result_array.append(num)

In [438]:
result_array

[10, 9, 6, 3, 8, 9, 5, 6]

#### 최종

In [40]:
import numpy as np
### 0. N*N matrix 만들기
def make_matrix(input_list,N):
    a=[[0]*N for i in range(N)] #파이썬 2차원 배열, 모든 원소가 0인 NxN리스트 생성
    a[-1] = input_list
    return a

In [41]:
### 1. 물고기의 수가 가장 적은 어항에 물고기를 한 마리 넣는다.
def add_one_to_min(input_matrix):
    result_matrix = np.copy(input_matrix)
    copy_list = input_matrix[-1].copy()
    for i,value in enumerate(input_matrix[-1]):
        if value== min(input_matrix[-1]):
            copy_list[i] = value+1
    result_matrix[-1] = copy_list
    return result_matrix

In [42]:
### 2. 어항을 쌓는다
def stack_fish_tank(input_matrix,N):
    result_matrix = np.copy(input_matrix)
    pivot,w,h = 1,1,1
    idx = 0
    while True:
        if (pivot-1+w+h>N): #종료 조건
            break
        for c in range(pivot-1, pivot-1 + w):
            for r in range(-1, -h - 1, -1):
                nextR = - w + c - pivot
                nextC = pivot-1 +w -(r+1)
                result_matrix[nextR][nextC] = result_matrix[r][c]
                result_matrix[r][c] = 0
        pivot += (idx // 2 + 1)
        if idx % 2 == 1:
            w += 1
        else:
            h += 1
        idx += 1
    return result_matrix

In [43]:
### 3. 어항에 있는 물고기 수 조절
def control_fish_num(input_matrix,N):
    result_matrix = np.copy(input_matrix)
    dx = [0,0,-1,1]
    dy = [1,-1,0,0]
    for x in range(0,N):
        for y in range(0,N):
            for i in range(0,4):
                nextX = x + dx[i]
                nextY = y + dy[i]
                if (nextX<0) or (nextX>N-1) or (nextY<0) or (nextY>N-1):
                    continue
                if (input_matrix[nextX][nextY] ==0):
                    continue
                if (input_matrix[x][y]> input_matrix[nextX][nextY]):
                    diff = (input_matrix[x][y] - input_matrix[nextX][nextY]) //5
                    result_matrix[x][y] -= diff
                    result_matrix[nextX][nextY] += diff
    return result_matrix

In [44]:
### 4. 어항을 바닥에 일렬로 놓기
def spread_fish(input_matrix,N):
    result_matrix = [[0]*N for i in range(N)]
    compare_list = [0]*N
    result_array = []
    for c in range(0,N):
        if np.array_equal(input_matrix[:,c],compare_list):
            continue
        for i in range(0,N):
            num = np.flip(input_matrix[:,c])[i]
            if num == 0:
                continue
            result_array.append(num)
    result_matrix[-1] = result_array
    return result_matrix

In [45]:
### 5. 공중 부양
# 180 도 회전
def rotate_180_clockwise(input_list):
    new_list = np.copy(input_list)
    new_list = np.flip(np.append(new_list,[0]*(N-len(input_list))))
    return new_list
def fly_fish_bowls(input_matrix, N):
      result_matrix = np.copy(input_matrix)
      compare_list = [0]*N
      while True:
            zero_row = 0 
            reversed_lists = []
            if np.count_nonzero(result_matrix[-1])== int(N/4):
                  break
            for i,row in enumerate(result_matrix):       
                  if np.array_equal(row, compare_list):
                        zero_row += 1
                  if not(np.array_equal(row,compare_list)):
                        nonzero_len = np.count_nonzero(row)
                        start = N - nonzero_len
                        copy_row = np.copy(row) #deep copy
                        list = copy_row[start:start + int(nonzero_len/2)]
                        result_matrix[i][start:start + int(nonzero_len/2)] =0
                        reversed_list = rotate_180_clockwise(list)
                        reversed_lists.append(reversed_list)
                        
                        nonzero_row = N-zero_row

            for i,list in enumerate(reversed_lists):
                  result_matrix[(-1)*(i+nonzero_row+1)][:] = list
      return result_matrix

In [46]:
def get_result(input_matrix):
    input_list = input_matrix[-1]
    result_diff = max(input_list)-min(input_list)
    return result_diff

In [511]:
N, K = input().split()
N, K = int(N), int(K)
print(N,K)

8 7


In [49]:
list1 = [1,2,3]
list2=[1,2,3]
list1==list2

True

In [10]:
input_list = list(map(int, input().split()))

In [11]:
input_list

[1, 2, 3, 4, 5, 6, 7, 8]

In [113]:
input_list = [1,10000,1,10000]
N=4
result_matrix = make_matrix(input_list,N)

In [79]:
answer = 0
#input_list = [5, 2, 3, 14, 9, 2, 11, 8]
input_list = [1,10000,1,10000]

N = 4
K = 0
result_matrix = make_matrix(input_list,N)

In [22]:
input_list = [5, 2, 3, 14, 9, 2, 11, 8]


In [48]:
answer = 0
#input_list = [5, 2, 3, 14, 9, 2, 11, 8]
input_list = [1, 1, 10000, 1 ,2 ,3 ,10000 ,9999, 10, 9 ,8 ,10000, 5, 4, 3, 1]

N = 16
K = 0
result_matrix = make_matrix(input_list,N)

while True:
    result = get_result(result_matrix)

    if result <= K:
        print(answer)
        break
    print(result_matrix)

    test_matrix_2 = add_one_to_min(result_matrix)
    stack_matrix = stack_fish_tank(test_matrix_2,N)
    control_matrix = control_fish_num(stack_matrix,N)
    spread_matrix = spread_fish(control_matrix,N)
    fly_matrix = fly_fish_bowls(spread_matrix,N)
    control_matrix_2 = control_fish_num(fly_matrix,N)
    result_matrix = spread_fish(control_matrix_2,N)

    answer += 1

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 10000, 1, 2, 3, 10000, 9999, 10, 9, 8, 10000, 5, 4, 3, 1]]
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [24]:
result_matrix

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [5, 2, 3, 14, 9, 2, 11, 8]]

In [46]:
input_matrix = np.array([
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [2,  10000,  2,  10000]])

In [38]:
result_matrix = np.copy(input_matrix)
pivot,w,h = 1,1,1
idx = 0
N=4
while True:
        if (pivot-1+w+h>N): #종료 조건
            print("종료",pivot,w,h)
            break
        for c in range(pivot-1, pivot-1 + w):
            for r in range(-1, -h - 1, -1):
                nextR = - w + c - pivot
                nextC = pivot-1 +w -(r+1)
                result_matrix[nextR][nextC] = result_matrix[r][c]
                result_matrix[r][c] = 0
        print(pivot,w,h)
        print(result_matrix)
        pivot += (idx // 2 + 1)
        if idx % 2 == 1:
            w += 1
        else:
            h += 1
        print(pivot,w,h)
        idx += 1

1 1 1
[[    0     0     0     0]
 [    0     0     0     0]
 [    0     1     0     0]
 [    0 10000     1 10000]]
2 1 2
2 1 2
[[    0     0     0     0]
 [    0     0     0     0]
 [    0     0 10000     1]
 [    0     0     1 10000]]
3 2 2
종료 3 2 2


In [5]:
from collections import deque
board= list()
board_data=[1,10000,1,10000]
for row in board_data:
    board.append(deque([row]))

In [6]:
board

[deque([1]), deque([10000]), deque([1]), deque([10000])]

In [9]:
import sys
from collections import deque

board = list()
board.append(deque(list(map(int, sys.stdin.readline().split()))))

In [37]:
from collections import deque
import sys
N, K = 4, 0 
direction = [(-1, 0), (1, 0), (0, -1), (0, 1)]
board= list()
board_data=[1,10000,1,10000]
board.append(deque(board_data))


# 물고기가 가장 적은 어항에 물고기 한 마리 넣기
def push_fish_to_min_bowl(graph):
    min_bowl_fish_num = min(graph[0])
    for i in range(len(graph[0])):
        if graph[0][i] == min_bowl_fish_num:
            graph[0][i] += 1


# 가장 왼쪽의 어항을 위에 쌓기
def popleft_and_stack(graph):
    pop = graph[0].popleft()
    graph.append(deque([pop]))


# 공중에 뜬 어항들을 시계방향 90도 회전하기
def rotate_90_clockwise(bowls):
    new_bowls = [[0] * len(bowls) for _ in range(len(bowls[0]))]
    for i in range(len(bowls[0])):
        for j in range(len(bowls)):
            new_bowls[i][j] = bowls[j][len(bowls[0])-1-i]

    return new_bowls


# 2개 이상 쌓인 어항들을 분리해서 공중부양 시키기
def fly_blocks(graph):
    while True:
        if len(graph) > len(graph[0]) - len(graph[-1]):
            break

        will_fly_blocks = []
        will_fly_blocks_row = len(graph)
        will_fly_blocks_col = len(graph[-1])

        for i in range(will_fly_blocks_row):
            new_deque = deque()
            for _ in range(will_fly_blocks_col):
                new_deque.append(graph[i].popleft())
            will_fly_blocks.append(new_deque)

        graph = [graph[0]]
        rotated_blocks = rotate_90_clockwise(will_fly_blocks)
        for row in rotated_blocks:
            graph.append(deque(row))

    return graph


# 공중 부양 작업이 끝난 뒤, 어항의 물고기 수 조절. BFS 수행. 역시 범인은 이 안에 있다. 음수가 나올리가 없다.
# 잠깐, 생각해보니 굳이 BFS 를 사용해야 돼? 걍 완탐하는게 목적인데.
def fix_fish_num(graph):
    dp = [[0] * len(graph[x]) for x in range(len(graph))]
    for x in range(len(graph)):
        for y in range(len(graph[x])):
            for d in direction:
                nx = x + d[0]
                ny = y + d[1]

                if 0 <= nx < len(graph) and 0 <= ny < len(graph[nx]):
                    # 현재 칸이 인접 칸보다 크다면
                    if graph[x][y] > graph[nx][ny]:
                        d = (graph[x][y] - graph[nx][ny]) // 5
                        if d >= 1:
                            dp[x][y] -= d
                    # 현재 칸이 인접 칸보다 작다면
                    else:
                        d = (graph[nx][ny] - graph[x][y]) // 5
                        if d >= 1:
                            dp[x][y] += d

    for i in range(len(graph)):
        for j in range(len(graph[i])):
            graph[i][j] += dp[i][j]


# 다시 어항을 일렬로 놓는다
def put_bowl_in_a_row(graph):
    new_graph = deque()

    for i in range(len(graph[-1])):
        for j in range(len(graph)):
            new_graph.append(graph[j][i])

    for i in range(len(graph[-1]), len(graph[0])):
        new_graph.append(graph[0][i])

    result_list = list()
    result_list.append(new_graph)

    return result_list


# 180 도 회전
def rotate_180_clockwise(graph):
    new_graph = []

    for i in reversed(range(len(graph))):
        graph[i].reverse()
        new_graph.append(graph[i])

    return new_graph


# 다시 공중부양 작업을 한다. 이번에는 절반을 자르는데 2번 수행한다.
def fly_blocks2(graph):
    left1 = list()
    left2 = list()
    new_deque1 = deque()
    for i in range(N//2):
        new_deque1.append(graph[0].popleft())
    left1.append(new_deque1)
    rotated_left1 = rotate_180_clockwise(left1)
    graph += rotated_left1

    for i in range(2):
        temp_deque = deque()
        for j in range(N//4):
            temp_deque.append(graph[i].popleft())
        left2.append(temp_deque)
    rotated_left2 = rotate_180_clockwise(left2)
    graph += rotated_left2


# 물고기가 가장 많은 어항과 가장 적은 어항의 차이를 구하는 함수
def get_result(graph):
    dq = graph[0]
    result1 = max(dq) - min(dq)
    
    return result1


answer = 0
while True:
    result = get_result(board)
    if result <= K:
        print(answer)
        break
    print("처음",answer,board)
    push_fish_to_min_bowl(board)
    print("1개씩 ",answer,board)
    popleft_and_stack(board)
    board = fly_blocks(board)
    fix_fish_num(board)
    board = put_bowl_in_a_row(board)
    print("첫 공중부양 후 조정 ",answer,board)
    fly_blocks2(board)
    fix_fish_num(board)
    board = put_bowl_in_a_row(board)
    print("두번째 공중부양 후 조정 ",answer,board)

    answer += 1

처음 0 [deque([1, 10000, 1, 10000])]
1개씩  0 [deque([2, 10000, 2, 10000])]
첫 공중부양 후 조정  0 [deque([4000, 6002, 6002, 4000])]
두번째 공중부양 후 조정  0 [deque([4000, 4400, 5602, 6002])]
처음 1 [deque([4000, 4400, 5602, 6002])]
1개씩  1 [deque([4001, 4400, 5602, 6002])]
첫 공중부양 후 조정  1 [deque([5442, 4561, 5522, 4480])]
두번째 공중부양 후 조정  1 [deque([4672, 5074, 4929, 5330])]
처음 2 [deque([4672, 5074, 4929, 5330])]
1개씩  2 [deque([4673, 5074, 4929, 5330])]
첫 공중부양 후 조정  2 [deque([5038, 4965, 5119, 4884])]
두번째 공중부양 후 조정  2 [deque([4914, 4994, 5009, 5089])]
처음 3 [deque([4914, 4994, 5009, 5089])]
1개씩  3 [deque([4915, 4994, 5009, 5089])]
첫 공중부양 후 조정  3 [deque([5022, 4982, 5039, 4964])]
두번째 공중부양 후 조정  3 [deque([4975, 5003, 5001, 5028])]
처음 4 [deque([4975, 5003, 5001, 5028])]
1개씩  4 [deque([4976, 5003, 5001, 5028])]
첫 공중부양 후 조정  4 [deque([5006, 4998, 5013, 4991])]
두번째 공중부양 후 조정  4 [deque([4994, 5002, 5002, 5010])]
처음 5 [deque([4994, 5002, 5002, 5010])]
1개씩  5 [deque([4995, 5002, 5002, 5010])]
첫 공중부양 후 조정  5 [deque([5003,